### ISSUE TITLE
v2.1.0 breaks compilation for Rider plugins — an explicit reference to intellij.rider is required

### ISSUE THREAD

**Issue by ForNeVeR** [JetBrains/intellij-platform-gradle-plugin#1774]
### What happened?

After updating to v2.1.0 in my Rider plugin (see [this commit](https://github.com/ForNeVeR/AvaloniaRider/commit/19a295495a22fee0724b5bc36c1e31a62b1263f1)), I see a new compilation failure. It looks like the plugin no longer automatically adds bundled product modules, even though I expect them to be auto-included. At least in the case of Rider, this is a must — there's no point in building a Rider plugin without referencing the `intellij.rider` product module.

Note that it is marked as a product module v2 in `product-info.json` of the corresponding Rider version:
```json
    {
      "name": "intellij.rider",
      "kind": "productModuleV2",
      "classPath": [
        "lib/modules/intellij.rider.jar"
      ]
    }
```

### Relevant log output or stack trace

```shell
> Task :compileKotlin
e: file:///home/runner/work/AvaloniaRider/AvaloniaRider/src/rider/main/kotlin/me/fornever/avaloniarider/idea/editor/AvaloniaPreviewEditorBase.kt:28:28 Unresolved reference: build
```

### Steps to reproduce

1. Check out [this commit](https://github.com/ForNeVeR/AvaloniaRider/commit/19a295495a22fee0724b5bc36c1e31a62b1263f1) of AvaloniaRider.
2. `./gradlew :assemble`
3. Observe the compilation error.

**Workaround:** add `bundledModule("intellij.rider")`

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.10.2

### Operating System

None

### Link to build, i.e. failing GitHub Action job

https://github.com/ForNeVeR/AvaloniaRider/actions/runs/11035451027/job/30651456122

**Comment by yodax** [comment]
After upgrading to the latest version, we experience this problem as well. Several parts of the SDK are no longer available to us. 

Most importantly:

- dotnet debugging
- wormhole
- systemenvironmentprovider

I suspect that this is due to the reason @ForNeVeR mentioned in his report, the entirety of the Rider framework isn't in the SDK as far as I can tell.

**Comment by ForNeVeR** [comment]
Now I see markup in my post has been broken. You might've missed the workaround: add `bundledModule("intellij.rider")`. For me it started to work after that.

**Comment by yodax** [comment]
Can confirm; the workaround works 👍

**Comment by hsz** [comment]
Thanks for reporting. This module will be now available for Rider automatically.
