### ISSUE TITLE
NoSuchMethodError: java.lang.Object kotlinx.coroutines.BuildersKt.runBlockingWithParallelismCompensation

### ISSUE THREAD

**Issue by PHPirates** [JetBrains/intellij-platform-gradle-plugin#1807]
### What happened?

After updating this plugin to 2.1.0 and the intellij dependency to 2024.2, I'm getting the following exception in tests. I'm not sure by which update this is caused, as I need to update this plugin in order to use 2024.2.

If I look at the [source](https://github.com/Kotlin/kotlinx.coroutines) of kotlinx.coroutines, indeed this method does not seem to exist (anymore) in coroutines 1.9.0. So why is internal JetBrains code trying to use it?

### Relevant log output or stack trace

```shell
Caused by: java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.BuildersKt.runBlockingWithParallelismCompensation(kotlin.coroutines.CoroutineContext, kotlin.jvm.functions.Function2)'
	at kotlinx.coroutines.internal.intellij.IntellijCoroutines.runBlockingWithParallelismCompensation(intellij.kt:41)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:146)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:139)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:85)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:139)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:122)
	at com.intellij.util.indexing.UnindexedFilesScanner$ScanningSession.collectIndexableFilesConcurrently(UnindexedFilesScanner.kt:289)
	at com.intellij.util.indexing.UnindexedFilesScanner$scan$1.invoke(UnindexedFilesScanner.kt:191)
	at com.intellij.util.indexing.UnindexedFilesScanner$scan$1.invoke(UnindexedFilesScanner.kt:184)
	at com.intellij.util.indexing.UnindexedFilesScanner.markStage(UnindexedFilesScanner.kt:552)
	at com.intellij.util.indexing.UnindexedFilesScanner.scan(UnindexedFilesScanner.kt:184)
	at com.intellij.util.indexing.UnindexedFilesScanner.scanUnindexedFiles(UnindexedFilesScanner.kt:252)
	at com.intellij.util.indexing.UnindexedFilesScanner.scanAndUpdateUnindexedFiles(UnindexedFilesScanner.kt:234)
	at com.intellij.util.indexing.UnindexedFilesScanner.access$scanAndUpdateUnindexedFiles(UnindexedFilesScanner.kt:59)
	at com.intellij.util.indexing.UnindexedFilesScanner$perform$1$1.invoke$lambda$0(UnindexedFilesScanner.kt:456)
	at com.intellij.util.gist.GistManagerImpl.runWithMergingDependentCacheInvalidations(GistManagerImpl.java:190)
	at com.intellij.util.indexing.UnindexedFilesScanner$perform$1$1.invoke(UnindexedFilesScanner.kt:455)
	at com.intellij.util.indexing.UnindexedFilesScanner$perform$1$1.invoke(UnindexedFilesScanner.kt:450)
	at com.intellij.util.indexing.UnindexedFilesScanner.prepareScanningHistoryAndRun(UnindexedFilesScanner.kt:488)
	at com.intellij.util.indexing.UnindexedFilesScanner.perform(UnindexedFilesScanner.kt:450)
	at com.intellij.util.indexing.UnindexedFilesScannerExecutorImpl$runScanningTask$2$2.invoke(UnindexedFilesScannerExecutorImpl.kt:222)
	at com.intellij.util.indexing.UnindexedFilesScannerExecutorImpl$runScanningTask$2$2.invoke(UnindexedFilesScannerExecutorImpl.kt:221)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:339)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:232)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:231)
	at com.intellij.util.indexing.UnindexedFilesScannerExecutorImpl$runScanningTask$2.invokeSuspend(UnindexedFilesScannerExecutorImpl.kt:221)
	at com.intellij.util.indexing.UnindexedFilesScannerExecutorImpl$runScanningTask$2.invoke(UnindexedFilesScannerExecutorImpl.kt)
	at com.intellij.util.indexing.UnindexedFilesScannerExecutorImpl$runScanningTask$2.invoke(UnindexedFilesScannerExecutorImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at com.intellij.util.indexing.UnindexedFilesScannerExecutorImpl.runScanningTask(UnindexedFilesScannerExecutorImpl.kt:209)
	at com.intellij.util.indexing.UnindexedFilesScannerExecutorImpl.access$runScanningTask(UnindexedFilesScannerExecutorImpl.kt:37)
	at com.intellij.util.indexing.UnindexedFilesScannerExecutorImpl$1$3$1.invokeSuspend(UnindexedFilesScannerExecutorImpl.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

### Steps to reproduce

Have some other dependencies which use `org.jetbrains.kotlinx:kotlinx-coroutines-core` as transitive dependency, then upgrade this plugin to 2.1.0 and intellij to 2024.2

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.10.2

### Operating System

Linux

### Link to build, i.e. failing GitHub Action job

https://github.com/Hannah-Sten/TeXiFy-IDEA/actions/runs/11333331140/job/31517251128

**Comment by YannCebron** [comment]
Most likely you have some transitive dependency on kotlinx-coroutines library somewhere https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#coroutinesLibraries

**Comment by PHPirates** [comment]
I just read https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#coroutinesLibraries and apparently kotlinx.coroutines is bundled now and is modified by jetbrains, which _does_ include this method: https://github.com/JetBrains/intellij-deps-kotlinx.coroutines
So the solution is to exclude manually from all transitive dependencies:

```
configurations {
    all {
        // https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#coroutinesLibraries
        exclude(group = "org.jetbrains.kotlinx", module = "kotlinx-coroutines-core")
    }
}
```
Hope this saves someone else some time. I just noticed that plugin verification warns about this as well.
