### ISSUE TITLE
[2.8.0 2.9.0] Custom testIde throws java.lang.ClassNotFoundException for bundled plugin

### ISSUE THREAD

**Issue by zielu** [JetBrains/intellij-platform-gradle-plugin#2022]
### What happened?

After upgrading to 2.8.0 custom testIde task started failing with java.lang.ClassNotFoundException for class from bundled plugin.
Same thing happens in 2.9.0.

[Test_repro1.patch](https://github.com/user-attachments/files/22181210/Test_repro1.patch)

### Relevant log output or stack trace

```shell
git4idea/repo/GitRepositoryManager
java.lang.NoClassDefFoundError: git4idea/repo/GitRepositoryManager
	at org.jetbrains.plugins.template.MyItTest.test(MyItTest.kt:20)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.testFramework.junit5.impl.TestLoggerInterceptor.intercept$lambda$0(TestLoggerInterceptor.kt:12)
	at com.intellij.testFramework.TestLoggerKt.recordErrorsLoggedInTheCurrentThreadAndReportThemAsFailures(testLogger.kt:81)
	at com.intellij.testFramework.junit5.impl.TestLoggerInterceptor.intercept(TestLoggerInterceptor.kt:11)
	at com.intellij.testFramework.junit5.impl.AbstractInvocationInterceptor.interceptTestMethod(AbstractInvocationInterceptor.kt:29)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassNotFoundException: git4idea.repo.GitRepositoryManager
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 8 more
```

### Steps to reproduce

1. Checkout main (02df6e80) from intellij-platform-plugin-template
2. Apply attached patch
3. Run integrationTests task
4. Notice NoClassDefFound
5. Downgrade to 2.7.2
6. Run integrationTests task
7. Notice test passing

### Gradle IntelliJ Plugin version

2.8.0 2.9.0

### Gradle version

8.14.3 9.0.0

### Operating System

macOS

**Comment by hsz** [comment]
Hey! The 2.8.0 release introduced changes to the custom test task's classpath composition. Before that version, the main classpath, if loading additional plugins or modules, was loading them from the main IntelliJ Platform used for building that plugin, like:

- IntelliJ Platform 2024.1
- Java plugin from 2024.1
- Git plugin from 2024.1

Then, if you created a custom run/test task targeting i.e. 2025.2, the IntelliJ Platform libs were loaded correctly from 2025.2, but plugins were inherited from the main classpath, still:

- IntelliJ Platform 2025.2
- Java plugin from 2024.1
- Git plugin from 2024.1

It was not possible to swap plugins from 2024.1 to 2025.2 automatically due to i.e. differences in modules/plugins layout, transitive dependencies, and so.
As of 2.8.0, custom test/run tasks, by default, load only the base IntelliJ Platform. In order to bring plugins back to their classpath, please add them explicitly, like:

```kotlin
val integrationTests by intellijPlatformTesting.testIde.registering {
    task {
        useJUnitPlatform { ... }
    }
    plugins {
        plugin(...)
        bundledPlugin(...)
        bundledModule(...)
    }
}
```

**Comment by zielu** [comment]
It solved the issue, thanks !

**Comment by zielu** [comment]
@hsz I'm having related issue with 2.9.0 and com.intellij.testFramework (com.intellij.mock too) classes when targeting 2023.3.8
`java.lang.NoClassDefFoundError: com/intellij/testFramework/fixtures/IdeaTestFixtureFactory`

No such problems when targeting 2024.3.

**Comment by jansorg** [comment]
I'm having the same problem. With 2.9.0 (here with 2024.2), a custom `testIde` task is now failing. Previously, 2.7.2 was working for this setup.

```
  pro.bashsupport.messages.ChineseMessagesTest

    ✘ initializationError
                                                                                                                                                                     
      java.lang.NoClassDefFoundError: com/intellij/testFramework/fixtures/LightPlatformCodeInsightFixture4TestCase                                                   
                                                                                                                                                                     
      Caused by: java.lang.ClassNotFoundException: com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixture4TestCase  
```

**Comment by jansorg** [comment]
I'm still seeing the NoClassDefFound with 2.9.0. Because a custom test task only offers `task {...}` and `plugins {...}`, there's no way to add the testframeworks back in

**Comment by hsz** [comment]
In the latest snapshot, the `testFramework()` helper is now available for custom tasks:

```kotlin
val integrationTests by intellijPlatformTesting.testIde.registering {
    testFramework(...)
    ...
}
```

**Comment by jansorg** [comment]
Thank you very much!

**Comment by hsz** [comment]
Thank you for highlighting that!

**Comment by zielu** [comment]
One thing I noticed is that `intellijPlatformTesting.testIde.registering` must come after `dependencies.intellijPlatform` declaration, otherwise I'm getting `Cannot change dependencies of dependency configuration ':<plugin-module-name>:intellijPlatformLocal' after it has been included in dependency resolution.`

Works fine otherwise. Thanks for the fix !
